"""first migration

Revision ID: a3d3cb989507
Revises: 
Create Date: 2024-07-29 21:24:16.453129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d3cb989507'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='users_party_id_fkey', table_name='users')
    op.drop_index('ix_parties_name', table_name='parties')
    op.drop_table('parties')
    op.drop_index('ix_users_token', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name='users_party_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_token', 'users', ['token'], unique=True)
    op.create_table('parties',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='parties_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='parties_pkey'),
    sa.UniqueConstraint('owner_id', name='parties_owner_id_key')
    )
    op.create_index('ix_parties_name', 'parties', ['name'], unique=True)
    # ### end Alembic commands ###
