services:
  deezify-backend:
    build: ./backend
    container_name: deezify-backend
    env_file: ./.env/backend.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - SPOTIFY_SCOPES=user-read-email user-read-private streaming app-remote-control user-read-playback-state user-modify-playback-state user-read-currently-playing
      - SPOTIFY_CALLBACK_URL=https://api.deezify.duckdns.org/login/spotify/callback
      - DEEZER_CALLBACK_URL=https://api.deezify.duckdns.org/login/deezer/callback
      - DEEZER_PERMS=email,basic_access
      - FRONTEND_URI=https://deezify.duckdns.org
      - DB_HOST=deezify-db
      - DB_NAME=deezify
    volumes:
      - ./backend:/workspace
    networks:
      - traefik_default
      - deezify_default
    restart: unless-stopped
    working_dir: /workspace
    command: sh /workspace/script.sh
  deezify-frontend:
    image: node:latest
    container_name: deezify-frontend
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - ORIGIN=https://deezify.duckdns.org
      - FRONTEND_URI=http://deezify.duckdns.org
      - VITE_BACKEND_URL=https://api.deezify.duckdns.org
      - VITE_SERVER_BACKEND_URL=http://deezify-backend:3000
    volumes:
      - ./frontend:/workspace
    networks:
      - traefik_default
      - deezify_default
    restart: unless-stopped
    working_dir: /workspace
    command: sh /workspace/script.sh
  deezify-db:
    image: postgres:latest
    container_name: deezify-db
    env_file: ./.env/db.env
    environment:
      - POSTGRES_DB=deezify
    volumes:
      - deezify-db:/var/lib/postgresql/data
    networks:
      - deezify_default
    restart: unless-stopped
  # Optional
  deezify-pgadmin:
    image: dpage/pgadmin4
    container_name: deezify-pgadmin
    env_file: .env/pgadmin.env
    ports:
      - 5050:80
    networks:
      - deezify_default
    restart: unless-stopped

volumes:
  deezify-db:
    driver: local
networks:
  traefik_default:
    name: traefik_default
    external: true
  deezify_default:
    name: deezify_default
    driver: bridge
