services:
  deezify-backend:
    image: python:3
    container_name: deezify-backend
    env_file: ./.env/backend.env
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - SPOTIFY_SCOPES=user-read-email
      - SPOTIFY_CALLBACK_URL=http://localhost:3000/login/spotify/callback
      - DB_HOST=deezify-db
      - DB_NAME=deezify
    volumes:
      - ./backend:/workspace
    restart: unless-stopped
    working_dir: /workspace
    command: sh /workspace/script.sh
  deezify-frontend:
    image: node:latest
    container_name: deezify-frontend
    env_file: ./.env/frontend.env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/workspace
    restart: unless-stopped
    working_dir: /workspace
    command: sh /workspace/script.sh
  deezify-db:
    image: postgres:latest
    container_name: deezify-db
    env_file: ./.env/db.env
    environment:
      - POSTGRES_DB=deezify
    volumes:
      - deezify-db:/var/lib/postgresql/data
    restart: unless-stopped
  # Optional
  deezify-pgadmin:
    image: dpage/pgadmin4
    container_name: deezify-pgadmin
    env_file: .env/pgadmin.env
    ports:
      - 5050:80
    restart: unless-stopped

volumes:
  deezify-db:
    driver: local
